# Generated by Django 6.0.5 on 2026-06-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
    ]
